name: Hello World Workflow

on: [push]

jobs:
  hello-world-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run Hello World
        run: echo "Hello, World!"
`