name: Infra Deployment

on:
  push:
    branches:
      - main
    paths:
      - ".devops/**"
      - ".github/**"

jobs:
  infra-deploy:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true
      ARM_ACCOUNT_KEY: ${{ secrets.ARM_ACCOUNT_KEY }}
    permissions:
      contents: write
      id-token: write # Necessary for actions/deploy-pages
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v3
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Initialize Terraform
        working-directory: ./.devops/azure
        run: terraform init
      - name: Terraform Validate
        working-directory: ./.devops/azure
        run: |
          terraform validate
      - name: Terraform Plan
        working-directory: ./.devops/azure
        run: |
          terraform plan
      - name: Deploy to Azure
        working-directory: ./.devops/azure
        run: |
          terraform apply -auto-approve -var="resource_group_name=${{ secrets.RESOURCE_GROUP_NAME }}" -var="aks_cluster_name=${{ secrets.AKS_CLUSTER_NAME }}"
      - name: Set AKS context
        id: set-context
        uses: azure/aks-set-context@v3
        with:
          resource-group: "${{ secrets.RESOURCE_GROUP_NAME }}"
          cluster-name: "${{ secrets.AKS_CLUSTER_NAME }}"
      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
      - name: Replace variables in Kubernetes deployment
        run: |
          export REGISTRY_LOGIN_SERVER=${{ secrets.REGISTRY_LOGIN_SERVER }}
          envsubst < .devops/kubernetes/deployment.yaml > .devops/kubernetes/deployment_replaced.yaml
      - name: Deploy to Kubernetes
        working-directory: ./.devops/kubernetes
        run: |
          kubectl delete secret acr-secret --ignore-not-found
          kubectl create secret docker-registry acr-secret \
            --docker-server=${{ secrets.REGISTRY_LOGIN_SERVER }} \
            --docker-username=${{ secrets.REGISTRY_USERNAME }} \
            --docker-password=${{ secrets.REGISTRY_PASSWORD }}
          kubectl apply -f deployment_replaced.yaml
