name: Validation and Deployment

on: 
  push:
    branches:
      - main

jobs:
  validate-python-files:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Validate Python files
        run: |
          python -m compileall src
    
  validate-terraform-files:
    runs-on: ubuntu-latest
    needs: validate-python-files
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3
      - run: terraform init
      - name: Validate Terraform files
        run: |
          terraform validate

  deployment:
    runs-on: ubuntu-latest
    needs: validate-terraform-files
    env:
      ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
      ARM_USE_OIDC: true
    permissions:
      contents: write
      id-token: write    # Necessary for actions/deploy-pages
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - uses: hashicorp/setup-terraform@v3
      - name: Azure CLI Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.ARM_CLIENT_ID }}
          tenant-id: ${{ secrets.ARM_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      - name: Initialize Terraform
        working-directory: ./.devops/azure
        run: terraform init
      - name: Terraform Import
        working-directory: ./.devops/azure
        run: |
          terraform import azurerm_resource_group.rg /subscriptions/${{ secrets.ARM_SUBSCRIPTION_ID }}/resourceGroups/devopsAgentRg
      - name: Terraform Plan
        working-directory: ./.devops/azure
        run: |
          terraform plan
      - name: Deploy to Azure
        working-directory: ./.devops/azure
        run: |
          terraform apply -auto-approve